services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      #- catalog-service
      - order-service
      - notification-service
      - payments-service
      - sellers-service

  #catalog-service:
   # build: ./catalog-service
    #ports:
     # - "3001:3001"
    #env_file:
     # - ./catalog-service/.env

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    env_file:
      - ./order-service/.env

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    env_file:
      - ./notification-service/.env

  payments-service:
    build: ./payments-service
    ports:
      - "3004:3004"
    env_file:
      - ./payments-service/.env

  sellers-service:
    build: ./sellers-service
    ports:
      - "3005:3005"
    env_file:
      - ./sellers-service/.env

  #frontend-client:
   # build: ./front-end
    #ports:
     # - "4200:4200"

 # frontend-sellers:
  #  build: ./front-end-sellers
   # ports:
    #  - "4300:4300"