services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./.env/api-gateway.env:/app/.env:ro
    depends_on:
      - catalog-service
      - order-service
      - notification-service
      - payments-service
      - sellers-service
  catalog-service:
    build: ./catalog-service
    ports:
      - "3001:3001"
    volumes:
      - ./.env/catalog-service.env:/app/.env:ro

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    volumes:
      - ./.env/order-service.env:/app/.env:ro

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    volumes:
      - ./.env/notification-service.env:/app/.env:ro

  payments-service:
    build: ./payments-service
    ports:
      - "3004:3004"
    volumes:
      - ./.env/payments-service.env:/app/.env:ro

  sellers-service:
    build: ./sellers-service
    ports:
      - "3005:3005"
    volumes:
      - ./.env/sellers-service.env:/app/.env:ro

  frontend-clients:
    build: ./frontend-clients
    ports:
      - 4200:80

  frontend-sellers:
    build:
      context: ./frontend-sellers
      args:
        # En local se usa "/" porque se accede directo por http://localhost:4300.
        # En producción se usa predeterminado "/vendedores/" porque la app se sirve bajo https://dominio/vendedores.
        BASE_HREF: /
    ports:
      - "4300:80"
