name: Build and Push to Artifact Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: northamerica-south1-docker.pkg.dev
  PROJECT_ID: pickteso-arquitectura
  REGISTRY_NAME: pickteso-arquitectura-registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - api-gateway
          - catalog-service
          - order-service
          - notification-service
          - payments-service
          - sellers-service
          - frontend-sellers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ matrix.service }}:${{ github.sha }}"
          LATEST_IMAGE="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REGISTRY_NAME }}/${{ matrix.service }}:latest"
          docker build -t $IMAGE_NAME -t $LATEST_IMAGE ./${{ matrix.service }}
          docker push $IMAGE_NAME
          docker push $LATEST_IMAGE
